### Глава 12 - Обработка ошибок и исключения

### Примеры из книги

#### Создание собственных исключений
* [Пример](examples/myself/InheritingException.java) - Создание собственного исключения
* [Пример](examples/myself/FullConstructors.java) - Создание собственного исключения с аргументом в конструкторе

#### Вывод информации об исключениях
* [Пример](examples/logging/LoggingExceptions.java) - Вывод информации об исключениях через объект Logger
* [Пример](examples/logging/LoggingExceptions2.java) - Регистрация перехваченных исключений
* [Пример](examples/logging/ExtraFeatures.java) - Расширение функциональности классов исключений

#### Перехват любого типа исключений
* [Пример](examples/trace/WhoCalled.java) - Программный доступ к информации трассировки стека

##### Трассировка стека


### Упражнения
* [1](exercises/ex1/MainApp.java) - Создайте класс с методом `main()`, возбуждающим исключение типа `Exception` из
блока `try`. Задайте в конструкторе для `Exception` строковый аргумент. Перехватите исключение в блоке `catch` и
распечатайте текст аргумента. Добавьте блок `finally` и выведите сообщение как доказательство его выполнения.
* [2](exercises/ex2/MainApp.java) - Определите ссылку на объект и присвойте ей значение `null`. Попробуйте вызвать
метод объекта, пользуясь этой ссылкой. Потом вставьте этот код в блок `try-catch` и перехватите исключение.
* [3](exercises/ex3/MainApp.java) - Напишите код, который генерирует и перехватывает исключение
`ArrayIndexOutOfBoundsException`.
* [4](exercises/ex4/MainApp.java) - Создайте ваш собственный класс исключения, используя ключевое слово `extends`.
Напишите конструктор, получающий строковый аргумент, и сохраните этот аргумент внутри объекта по ссылке на `String`.
Напишите метод, который выводит эту строку. Подсоедините новый блок `try-catch` для проверки нового исключения.
* [5](exercises/ex5/MainApp.java) - Создайте собственную реализацию модели возобновления, используя цикл `while`,
который выполняется до тех пор, пока исключение не перестанет выполняться.
* [6](exercises/ex6/MainApp.java) - Создайте два класса исключения, каждый из которых автоматически выводит информацию
о себе. Продемонстрируйте как данные классы работают.
* [7](exercises/ex7/MainApp.java) - Измените упражнение 3 так, чтобы информация об исключении выводилась в блоке `catch`.
* [8](exercises/ex8/MainApp.java) - Напишите класс с методом, который возбуждает исключение, созданное вами в
упражнении 4. Попробуйте откомпилировать его без спецификации исключений и посмотрите, что "скажет" компилятор. После
этого добавьте необходимую спецификацию исключений. Протестируйте свой класс и его исключение внутри блока `try-catch`.
* [9](exercises/ex9/MainApp.java) - Создайте три новых типа исключений. Напишите класс с методом, возбуждающим каждое
из них. В методе `main()` вызовите этот метод, используя одно предложение `catch`, способное перехватить все три
исключения.


